### ISSUE TITLE
Not build on FreeBSD

### ISSUE THREAD

**Issue by Heic0** [tx00100xt/SeriousSamClassic#1]
https://pastebin.com/aan8yy2h

**Comment by tx00100xt** [comment]
Unfortunately I don't have Macos and bsd installed. The build scripts and file are from the ptitseb fork.
The log shows that the error occurs at the linking stage. I recently changed the linking and made the Engine library dynamic. 
Perhaps the static linking that was before will fix the errors.
You can try the old mac file, where there is a static link.

Perhaps this will solve the problem with the SDL and the ZLIB.
[CMakeLists.txt](https://github.com/tx00100xt/SeriousSamClassic/files/8742009/CMakeLists.txt)

**Comment by Heic0** [comment]
I can run the game on FreeBSD, but there are bugs with the animation model and the network system in the game does not work.
I enclose a tail log for you

CUnixDynamicLoader error: Undefined symbol "_nss_cache_cycle_prevention_function"
Cannot start game:
Cannot load DLL file '/usr/home/vitek/Game/Serious Sam Classic Open source/Bin/libEntitiesMP.so':
Undefined symbol "_nss_cache_cycle_prevention_function"

**Comment by Heic0** [comment]
I also recorded a gameplay video on FreeBSD
https://disk.yandex.com/i/76ZcCBAnNn-M_w

**Comment by tx00100xt** [comment]
I installed FreeBSD on a virtual machine. Fixed CMakeLists.txt and added a definition for FreeBSD.
https://github.com/tx00100xt/SeriousSamClassic/commit/128e3bcc4cdccf2373706e6f896894fc23ea79b5
I didn't find any problems with the weapon. [See Video](https://disk.yandex.ru/i/2ZERZgIDStT2og)
I saw a weapons from the XPLUS mod on your video.
To build with standard weapons, you need to use EntitiesMP/PlayerWeapons_old.es with headers  Sources/Models/Weapons.
To build with XPLUS weapons, you need to use EntitiesMP/PlayerWeaponsHD.es with headers  Sources/Models/WeaponsHD.
Look at the scripts [build-linux64.sh](https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/build-linux64.sh) and [build-linux64xplus.sh](https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/build-linux64xplus.sh)

> CUnixDynamicLoader error: Undefined symbol "_nss_cache_cycle_prevention_function"
Cannot start game:
Cannot load DLL file '/usr/home/vitek/Game/Serious Sam Classic Open source/Bin/libEntitiesMP.so':
Undefined symbol "_nss_cache_cycle_prevention_function"
> 
I think the answer is probably here.
https://stackoverflow.com/questions/3559147/dlerror-undefined-symbol-nss-cache-cycle-prevention-function-on-freebsd-7-2

**Comment by tx00100xt** [comment]
> PIX apixAspectRatios[][2] = { 4, 3, 5, 4, 16, 9, 16, 10, 21, 9,  };
> 

That's not enough. To support 5:4 resolution, you need to create an ajuster table. Look at the function SetAdjusters() in 
SeriousSam.cpp.  Each ajuster needs to be debugged visually.

**Comment by tx00100xt** [comment]
I'm closing this issue.
> Not build on  FreeBSD
>
Fixed https://github.com/tx00100xt/SeriousSamClassic/commit/128e3bcc4cdccf2373706e6f896894fc23ea79b5
> network system in the game does not work.
>
>CUnixDynamicLoader error: Undefined symbol "_nss_cache_cycle_prevention_function"
Cannot start game:
Cannot load DLL file '/usr/home/vitek/Game/Serious Sam Classic Open source/Bin/libEntitiesMP.so':
Undefined symbol "_nss_cache_cycle_prevention_function"
>
Fixed https://github.com/tx00100xt/SeriousSamClassic/commit/874abecc9de3ad3f9c8834bce380a0c26019a1e5

For different models of weapons, you need to use different Entities (PlayerWeapons or PlayerWeaponsHD) .
To support 5:4 resolution you can create a new issue.

**Comment by tx00100xt** [comment]
Build on FreeBSD and Network supoort completed.
