### ISSUE TITLE
RPM for Alt Sisyphus build fails

### ISSUE THREAD

**Issue by Arbars** [tx00100xt/SeriousSamClassic#10]
Hello! One small trouble...

I'm trying to build an RPM package for ALT Sisyphus (cheers from @mshigorin!). And in the end I got this:

verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZTI19CMovableModelEntity
verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN7CEntity21SetPlacement_internalERK12CPlacement3DRK6MatrixIfLi3ELi3EEi
verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN14CMovableEntity4CopyER7CEntityj
verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN19CMovableModelEntity6Read_tEP8CTStream
And this error for all libraries of game.

And one more type of error igot in the end of packaging:
verify-elf: WARNING: ./usr/bin/DedicatedServer: RPATH entry found: $ORIGIN
verify-elf: WARNING: ./usr/bin/SeriousSamTFE: RPATH entry found: $ORIGIN

Repo with project: https://git.altlinux.org/people/arbars/packages/eriousSamClassic.git

Until now I trying to build TFE
P.S. Если можно, объясни на пальцах, что не так.

**Comment by tx00100xt** [comment]
> verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZTI19CMovableModelEntity
> verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN7CEntity21SetPlacement_internalERK12CPlacement3DRK6MatrixIfLi3ELi3EEi
> verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN14CMovableEntity4CopyER7CEntityj
> verify-elf: ERROR: ./usr/lib64/libEntities.so: undefined symbol: _ZN19CMovableModelEntity6Read_tEP8CTStream

Нужно добавить в начало спек файла строчку
>%set_verify_elf_method unresolved=relaxed
> 
как у самбы к примеру http://www.sisyphus.ru/ru/srpm/Sisyphus/samba/spec

> verify-elf: WARNING: ./usr/bin/DedicatedServer: RPATH entry found: $ORIGIN
> verify-elf: WARNING: ./usr/bin/SeriousSamTFE: RPATH entry found: $ORIGIN

в CMakeLists.txt нужно заменить -rpath,$ORIGIN на -rpath=/tmp
https://github.com/tx00100xt/serioussam-overlay/blob/main/games-fps/serioussam-tfe/files/rparh_security_2.patch

В спек файле и CMakeLists.txt неверно заданы конечные пути установки и неправильное имя для исполняемого файла.
>Нужно привести к такому виду:
For TFE (Folder Bin):
SeriousSam -> /usr/bin/serioussam
libEngine.so -> /usr/lib64/serioussam/libEngine.so
libEntities.so -> /usr/lib/64//serioussam/libEntities.so
libGame.so -> /usr/lib64//serioussam/libGame.so
Data files:
All game data (content from CD) -> /usr/share/serioussam/

>For TSE (Folder Bin):
SeriousSam -> /usr/bin/serioussamse
libEngineMP.so -> /usr/lib64/serioussamse/libEngineMP.so
libEntitiesMP.so -> /usr/lib64//serioussamse/libEntitiesMP.so
libGameMP.so -> /usr/lib64//serioussamse/libGameMP.so
Data files:
All game data (content from CD) -> /usr/share/serioussamse/

>ibamp11lib.so -> /usr/lib64/libamp11lib.so
libShaders.so -> /usr/lib64/libShaders.so

Можно посмотреть как это реализовано в генту:
https://bugs.gentoo.org/854567#c13
и немножко по другому тут:
https://github.com/tx00100xt/serioussam-overlay

**Comment by tx00100xt** [comment]
Я с библиотеками перепутал, подзабыл, давно ебилды делал.
libEngineMP.so и libEngine.so  должны быть в /usr/lib64 так как они подгружаются первыми и должны быть в стандартном каталоге поиска, а при загрузке других добавляется внутреннее имя игры .
В генту у меня сейчас так:
>For TFE:
SeriousSam -> /usr/bin/serioussam
libEngine.so -> /usr/lib64/libEngine.so
libEntities.so -> /usr/lib/64/serioussam/libEntities.so
libGame.so -> /usr/lib64/serioussam/libGame.so
ibamp11lib.so -> /usr/lib64/serioussam/libamp11lib.so
libShaders.so -> /usr/lib64/serioussam/libShaders.so
Data files:
All game data (content from CD) -> /usr/share/serioussam/

>For TSE :
SeriousSam -> /usr/bin/serioussamse
libEngineMP.so -> /usr/lib64/libEngineMP.so
libEntitiesMP.so -> /usr/lib64/serioussamse/libEntitiesMP.so
libGameMP.so -> /usr/lib64/serioussamse/libGameMP.so
ibamp11lib.so -> /usr/lib64/serioussamse/libamp11lib.so
libShaders.so -> /usr/lib64/serioussamse/libShaders.so
Data files:
All game data (content from CD) -> /usr/share/serioussamse/



> И вдогонку. Можно ли оформить поиск данных игры по домашнему каталогу, чтобы пользователю не нужно было лезть в корень системы?

Это нужно код игры переписывать, в генту отдельный ебилд читает данные образа и размещает их в /usr/share

**Comment by Arbars** [comment]
> можно попробовать
> 
> > _fnmApplicationPath = _fnmUserDir; // all game data
> 
> или так
> 
> > _fnmApplicationPath = _fnmUserDir + "/"; // all game data

Чисто по хорошему стоит сделать, как в gzdoom - данные игры ищутся по заданным в коде путям, в том числе и в домашнем каталоге пользователя, а там уже сам пользователь решает, куда их класть.

**Comment by Arbars** [comment]
Надо будет, кстати, разобраться с музыкой...

**Comment by tx00100xt** [comment]
> Надо будет, кстати, разобраться с музыкой...

За музыку отвечают libvorbisfile.so (ogg) и libamp11lib.so  (mp3) - можно посмотреть в логе грузяться они или нет
~/.local/share/Serious-Engine/serioussam/SeriousSam.log
~/.local/share/Serious-Engine/serioussamse/SeriousSam.log

Глянул SeriousSamClassic.spec - там отсутствуют строчки для TSE
install -D -m0755 ./SamTSE/Sources/%_arch-alt-linux/Debug/libShaders.so %buildroot%_libdir/serioussamse
install -D -m0755 ./SamTSE/Sources/%_arch-alt-linux/Debug/libamp11lib.so %buildroot%_libdir/serioussamse
и в %files The-Second-Encounter
%_libdir/serioussamse/libShaders.so
%_libdir/serioussamse/libamp11lib.so

**Comment by Arbars** [comment]
> За музыку отвечают libvorbisfile.so (ogg) и libamp11lib.so (mp3) - можно посмотреть в логе грузяться они или нет

А вот и лог:
```

CUnixDynamicLoader error: libvorbisfile.so: cannot open shared object file: No such file or directory
OGG playing disabled: Cannot load vorbisfile shared library: libvorbisfile.so: cannot open shared object file: No such file or directory.
```


> Глянул SeriousSamClassic.spec - там отсутствуют строчки для TSE
> install -D -m0755 ./SamTSE/Sources/%_arch-alt-linux/Debug/libShaders.so %buildroot%_libdir/serioussamse
> install -D -m0755 ./SamTSE/Sources/%_arch-alt-linux/Debug/libamp11lib.so %buildroot%_libdir/serioussamse
> и в %files The-Second-Encounter
> %_libdir/serioussamse/libShaders.so
> %_libdir/serioussamse/libamp11lib.so

О! А вот за указание на этот косяк - отдельное спасибо!

**Comment by Arbars** [comment]
В общем, пакеты собираются, основные игры на х86 архитектурах работают. Теперь осталось добиться сборки на Raspberry Pi...

**Comment by tx00100xt** [comment]
Для сборки на Raspberry Pi. нужно использовать ключ -DRPI4=TRUE
Достаточно заменить в spec: 
>cmake .. -DTFE=TRUE -DCMAKE_BUILD_TYPE=Release
>
на
>if [ "$HOSTTYPE" == "arm" -o "$HOSTTYPE" == "aarch64" ]; then
    cmake .. -DTFE=TRUE -DRPI4=TRUE -DCMAKE_BUILD_TYPE=Release
else
    cmake .. -DTFE=TRUE -DCMAKE_BUILD_TYPE=Release
fi

Для архитектуры e2k дополнительно делать ничего не нужно, все определения уже есть в коде
https://github.com/tx00100xt/SeriousSamClassic/commit/505de945636f65f5178c31b8bc34e8424c770c62
и
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/7a0708bb121025928fa707236d86de7f1d8ab386
всё работает как говорится из коробки: https://www.youtube.com/watch?v=_3W_GfnRWNI


> Чисто по хорошему стоит сделать, как в gzdoom - данные игры ищутся по заданным в коде путям, в том числе и в домашнем каталоге пользователя, а там уже сам пользователь решает, куда их класть

Когда будет побольше свободного времени - сделаю, это несложно.
