### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by GREATDNG** [tx00100xt/SeriousSamClassic#13]
I downloaded ready-made binaries, copied the game files there. No music only, other sound effects are present.

How to fix this?

**Comment by tx00100xt** [comment]
Please show the game log. On windows, it is located in the root directory of the game. On Linux, ~/.local/share/Serious-Engine/serioussam/SeriousSam.log and ~/.local/share/Serious-Engine/serioussamse/SeriousSam.log. The game log can be attached to the message as a text file.

**Comment by GREATDNG** [comment]
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic/files/10766966/SeriousSam.log). The system already has libvorbisfile3 installed.

**Comment by tx00100xt** [comment]
If you look at the list of files in the package:
https://packages.debian.org/sid/amd64/libvorbisfile3/filelist
Then you can see that there is no symbolic reference:
libvorbisfile.so -> libvorbisfile.so.3

### Solution:
`cd "/home/dng/Serious Sam/SamTFE/Bin"`
`ln -sf /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 libvorbisfile.so`
`cd "/home/dng/Serious Sam/SamTSE/Bin"`
`ln -sf /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 libvorbisfile.so`

or

`cd /usr/lib/x86_64-linux-gnu/`
`sudo ln -sf libvorbisfile.so.3 libvorbisfile.so`

or

`cd /usr/lib/x86_64-linux-gnu`
`cp libvorbisfile.so.3 "/home/dng/Serious Sam/SamTFE/Bin/libvorbisfile.so"`
`cp libvorbisfile.so.3 "/home/dng/Serious Sam/SamTSE/Bin/libvorbisfile.so"`

**Comment by tx00100xt** [comment]
And according to the log, they forgot to copy the file: [SE1_10b.gro](https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/SE1_10b.gro) in SamTFE and SamTSE folder.

**Comment by GREATDNG** [comment]
Thank you very much, the second method solved the problem.
