### ISSUE TITLE
Can't start Serious Sam TSE, fatal error

### ISSUE THREAD

**Issue by vini1264** [tx00100xt/SeriousSamClassic#14]
First Encounter windows binaries works just fine but every time I start second encounter it gives me a fatal error with the following message:

Cannot initialize classes:

Cannot load DLL file 'Entities.dll'

**Comment by tx00100xt** [comment]
You forgot to place the ModEXT.txt file with MP value inside the file, in the root directory of the game. This is a suffix for game library names.

For Sam TFE ModEXT.txt - empty. https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/ModEXT.txt
For Sam TFE ModEXT.txt - contains MP. https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/ModEXT.txt

Also, don't forget to copy the SE1_10b.gro file to the root directory of the game. 
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/SE1_10b.gro
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/SE1_10b.gro

**Comment by tx00100xt** [comment]
> In my opinion It would be better If those files were packaged alongside the binaries present in the releases tab, so I don't need to download them separately from the repository.

Ready. Now **SeriousSamClassic-1.10.4-win32-bin.zip** and **SeriousSamClassic-1.10.4-win64-bin.zip** archives contain ModEXT.txt and SE1_10b.gro files. https://github.com/tx00100xt/SeriousSamClassic/releases/tag/v1.10.4

**Comment by vini1264** [comment]
> > In my opinion It would be better If those files were packaged alongside the binaries present in the releases tab, so I don't need to download them separately from the repository.
> 
> Ready. Now **SeriousSamClassic-1.10.4-win32-bin.zip** and **SeriousSamClassic-1.10.4-win64-bin.zip** archives contain ModEXT.txt and SE1_10b.gro files. https://github.com/tx00100xt/SeriousSamClassic/releases/tag/v1.10.4

Great, thank you! I would also suggest to package with the Windows binaries the other folders from the repository like "Controls", "Data", "Demos", "Players", "SaveGame" and "Scripts". Specially the Controls, Players, SaveGame and Scripts folders since they are required to store the saves files, bindings, player data and configuration ini files on Windows.

**Comment by tx00100xt** [comment]
There is no need for this, since all these directories are on the CD, and in the GOG and Steam versions of the games. But the SE1_10b.gro file is really needed. Since the problem is solved, I think the issue can be closed. Have a good game.
