### ISSUE TITLE
cross-multiplayer not work

### ISSUE THREAD

**Issue by Heic0** [tx00100xt/SeriousSamClassic#3]
I can`t cross-connecting with a Linux system and FreeBSD  it a not possible !

response from my server
---
Server: Sent initialization info to '192.168.0.3' (2k)
Sending statedelta response
Server: Sent connection data to '192.168.0.3' (2406k->758k->95k)
Server: Sent initialization info to '192.168.0.3' (2k)
Sending statedelta response
Server: Sent connection data to '192.168.0.3' (2406k->758k->95k)

response from my client
---
joining session at '192.168.0.8'
sending statestate delta request
Cannot join game:
CRC error in DIFF!

**Comment by tx00100xt** [comment]
When I was fixing the network support for FreeBSD I changed the sendto function to GameAgent.cpp.
https://www.freebsd.org/cgi/man.cgi?query=sendto Perhaps it affected.
Rebuild the game using the latest commit for Linux, and for FreeBSD.  https://github.com/tx00100xt/SeriousSamClassic/commit/05c8b36cca216b960ee099b70c8b942c92bb23e9

Everything works. I started Linux Dedicated server in console. Connected to the server via master server table on Linux, the connected to the server from  Freebsd. In the screenshot, the left window is a Linux game. The right window is a game under FreeBSD on virtualbox
![Снимок экрана в 2022-05-25](https://user-images.githubusercontent.com/105300480/170208896-da00abe1-00c4-4dcb-ba08-e9b6fb5006c4.png)

**Comment by Heic0** [comment]
hmm strange doesn`t work for me .
I`m sure made a rebuild for all systems !

**Comment by Heic0** [comment]
It’s strange, network works, but when I’m make to connect from another system it don`t possible !

**Comment by tx00100xt** [comment]
I don't have the ability to provide support for FreeBSD. I don't use this system. I'm closing this issue.
