### ISSUE TITLE
unable to adjust gamma brightness and contrast

### ISSUE THREAD

**Issue by spinktvis** [tx00100xt/SeriousSamClassic#4]
First of all let me say thanks for this project, it's running great and everything seems to work fine so far. The only issue I've run across is that I'm unable to adjust gamma brightness and contrast in the settings. It happens both on the OpenGL as Vulkan binaries. So I'm not sure if it's unimplemented as of yet or bugged.

Running on Arch with GOG SS TFE. If you need additional information let me know.

**Comment by tx00100xt** [comment]
The advanced display options Brightness, Contrast, Red Offset, Green Offset, Blue Offset, Levels are only available in DirectX. These options are also not available on Windows with OpenGL. On Windows with OpenGL mode, only saturation and gamma are available. On Linux, only saturation is available in OpenGL and Vulkan.

**Comment by spinktvis** [comment]
Thanks so much for the explanation. Closing this.
