### ISSUE TITLE
hud icons do not scale with their boxes properly.

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic#6]
As the title suggests. As a side note. is it possible to allow for leaderboard hud removal?
Im talking about weapon icons specificly, which are cut off.

**Comment by tx00100xt** [comment]
>hud icons do not scale with their boxes properly.
>
Initially, the scaling of the top line of the hud containing the points and the leaderboard is not provided for either in Windows or in Linux.
>As the title suggests. As a side note. is it possible to allow for leaderboard hud removal?
>Im talking about weapon icons specificly, which are cut off.
>
At the moment it is not possible. But this is very easy to do if you introduce a new variable and change a few lines of code.
Changes must be entered here:
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/Entities/Common/HUD.cpp#L1049
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/Entities/Common/HUD.cpp#L1071

https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/Sources/EntitiesMP/Common/HUD.cpp#L1366
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/Sources/EntitiesMP/Common/HUD.cpp#L1388

If you are interested in building from source, I can make changes to the code and add this feature.

**Comment by LethalManBoob** [comment]
I can build from source. :)

**Comment by tx00100xt** [comment]
Good. As soon as I have time I will write the code and make a commit.

**Comment by tx00100xt** [comment]
I added the code to remove the top line hud.
https://github.com/tx00100xt/SeriousSamClassic/commit/4e51610d9e5629d75e6b739627f6e6e5eec8a880
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/a605fc18e394377d7f77bed673f8230291f52747
Now you need to enter in the console during the game:
hud_bShowKills=0
hud_bShowScore=0
After that, the number of monsters and the leaderboard will disappear. It is enough to enter the commands once, the settings will be saved

**Comment by LethalManBoob** [comment]
Hey i build it from source from the git repo (aur hasnt been updated yet) and its giving me this error.
Cannot initialize classes:
Cannot load DLL file '/home/joseph/SeriousSamClassic-VK/SamTFE/Bin/libEntities.so':
/home/joseph/SeriousSamClassic-VK/SamTFE/Bin/libEntities.so: cannot open shared object file: No such file or directory

**Comment by tx00100xt** [comment]
If script ./build-linux64.sh was used, then the key was specified -DTFE=TRUE ?
The Bin directory contains libEntities.so or libEntitiesMP.so ?

**Comment by LethalManBoob** [comment]
This was an error on my end. It works now. The new cvars work fine though the guns still are not scaled.

**Comment by tx00100xt** [comment]
Weapons and should not scale, only the hud.

**Comment by LethalManBoob** [comment]
I mean the weapon icons in the hud. Because they do not scale with their boxes. You can see the cut off of things like the pistol and shotgun

**Comment by LethalManBoob** [comment]
One more issue. 
Im compiling TFE and TSE the exact same way. I went over it twise following instructions. TFE works just fine but TSE lacks 2 .so files that are found in the aur build. libGameMP.so and libEntitiesMP.so

**Comment by tx00100xt** [comment]
> I mean the weapon icons in the hud. Because they do not scale with their boxes. You can see the cut off of things like the pistol and shotgun

Weapon icons inside boxes scale. And the fact that they are a little cut off inside is intended.

**Comment by tx00100xt** [comment]
Build sequence for TSE:
>git clone https://github.com/tx00100xt/SeriousSamClassic-VK.git
> cd SeriousSamClassic-VK/SamTSE/Sources
>./build-linux64.sh
>./build-linux64xplus.sh
>cd ..
>ls -l Bin
>ls -l Mods/XPLUS/Bin

**Comment by LethalManBoob** [comment]
SeriousSamVK on aur keeps wanting to update every time i run my updater but it stays on 1.10.2-1 it keeps trying to get 1.10.2-2 but it wont
