### ISSUE TITLE
Windows builds, please!

### ISSUE THREAD

**Issue by DI555** [tx00100xt/SeriousSamClassic#8]
Could it be possible to provide and Windows builds of SeriousSamClassic either, 32 and 64 bits, please!
It could get much more popularity to the game!

**Comment by tx00100xt** [comment]
Added support for Windows.
You can download the build in the releases section:

https://github.com/tx00100xt/SeriousSamClassic/releases/tag/v1.10.4

**Comment by DI555** [comment]
Great news ever!!!
i hope multiplayer between win and nix will work fine afrer all 👍👍👍

**Comment by tx00100xt** [comment]
Unfortunately the multiplayer engine code is compiler dependent. Depends on compiler optimizations. Compatibility between nix systems is possible when optimizing to -O1.
There is no compatibility between win and nix. You can read an interesting article about the multiplayer engine code of a serious sem here:  https://staniks.github.io/articles/serious-engine-networking-analysis.html
