### ISSUE TITLE
Fails to build on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [tx00100xt/SeriousSamClassic#9]
i follow the commands that are on your readme
Im running debian Buster 10

```
cd SeriousSamClassic/SamTFE/Sources
./build-linux64.sh -DTFE=TRUE -DRPI4=TRUE	# use build-linux32.sh for 32-bits
```

and i get this 
```
Will build with 'make -j4' ... please edit this script if incorrect.
+ rm -rf cmake-build
+ mkdir cmake-build
+ cd cmake-build
+ cp -vfr ../Entities/PlayerWeapons_old.es ../Entities/PlayerWeapons.es
'../Entities/PlayerWeapons_old.es' -> '../Entities/PlayerWeapons.es'
+ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-mmmx -DCMAKE_CXX_FLAGS=-mmmx -DUSE_I386_NASM_ASM=TRUE .. -DTFE=TRUE -DRPI4=TRUE
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_90c3e/fast && /usr/bin/make -f CMakeFiles/cmTC_90c3e.dir/build.make CMakeFiles/cmTC_90c3e.dir/build
    make[1]: Entering directory '/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_90c3e.dir/testCCompiler.c.o
    /usr/bin/cc   -mmmx    -o CMakeFiles/cmTC_90c3e.dir/testCCompiler.c.o   -c /home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp/testCCompiler.c
    cc: error: unrecognized command line option ‘-mmmx’
    make[1]: *** [CMakeFiles/cmTC_90c3e.dir/build.make:66: CMakeFiles/cmTC_90c3e.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_90c3e/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeError.log".
````

here is the CMakeError.log
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -mmmx
Id flags:  

The output was:
1
cc: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -mmmx
Id flags: -c 

The output was:
1
cc: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -mmmx
Id flags: -Aa 

The output was:
1
cc: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -mmmx
Id flags: -D__CLASSIC_C__ 

The output was:
1
cc: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -mmmx
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
1
cc: error: unrecognized command line option â€˜-mmmxâ€™
cc: error: unrecognized command line option â€˜--target=arm-arm-none-eabiâ€™


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -mmmx
Id flags:  

The output was:
1
c++: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -mmmx
Id flags: -c 

The output was:
1
c++: error: unrecognized command line option â€˜-mmmxâ€™


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -mmmx
Id flags: --c++ 

The output was:
1
c++: error: unrecognized command line option â€˜-mmmxâ€™
c++: error: unrecognized command line option â€˜--c++â€™


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -mmmx
Id flags: --ec++ 

The output was:
1
c++: error: unrecognized command line option â€˜-mmmxâ€™
c++: error: unrecognized command line option â€˜--ec++â€™; did you mean â€˜-Weffc++â€™?


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -mmmx
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
1
c++: error: unrecognized command line option â€˜-mmmxâ€™
c++: error: unrecognized command line option â€˜--target=arm-arm-none-eabiâ€™


Determining if the C compiler works failed with the following output:
Change Dir: /home/pi/RetroPie-Setup/tmp/build/samtfe/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_69832/fast && /usr/bin/make -f CMakeFiles/cmTC_69832.dir/build.make CMakeFiles/cmTC_69832.dir/build
make[1]: Entering directory '/home/pi/RetroPie-Setup/tmp/build/samtfe/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_69832.dir/testCCompiler.c.o
/usr/bin/cc   -mmmx    -o CMakeFiles/cmTC_69832.dir/testCCompiler.c.o   -c /home/pi/RetroPie-Setup/tmp/build/samtfe/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp/testCCompiler.c
cc: error: unrecognized command line option â€˜-mmmxâ€™
make[1]: *** [CMakeFiles/cmTC_69832.dir/build.make:66: CMakeFiles/cmTC_69832.dir/testCCompiler.c.o] Error 1
make[1]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/samtfe/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_69832/fast] Error 2
```

**Comment by tx00100xt** [comment]
> + cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-mmmx -DCMAKE_CXX_FLAGS=-mmmx -DUSE_I386_NASM_ASM=TRUE .. -DTFE=TRUE -DRPI4=TRUE

> 
You run  build-linux32.sh .
You are using Debian Buster 10 32-bit version?

If yes, then open the build-linux32.sh file in the editor and change line 
>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-mmmx -DCMAKE_CXX_FLAGS=-mmmx -DUSE_I386_NASM_ASM=TRUE .. $1 $2
>
to 
>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DUSE_I386_NASM_ASM=FALSE .. $1 $2
>

If you are using Debian Buster 10 64-bit, use the command:

> ./build-linux64.sh -DTFE=TRUE -DRPI4=TRUE

>

**Comment by Exarkuniv** [comment]
Thank you for the info. When I'm back I front of my pi I'll give that a shot and let you know

**Comment by Exarkuniv** [comment]
it is a 32bit verions

i changed what you said 
```
pi@retropie:~/SeriousSamClassic/SamTFE/Sources $ ./build-linux32.sh -DTFE=TRUE -DRPI4=TRUE
Will build with 'make -j4' ... please edit this script if incorrect.
+ rm -rf cmake-build
+ mkdir cmake-build
+ cd cmake-build
+ cp -vfr ../Entities/PlayerWeapons_old.es ../Entities/PlayerWeapons.es
'../Entities/PlayerWeapons_old.es' -> '../Entities/PlayerWeapons.es'
+ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DUSE_I386_NASM_ASM=FALSE .. -DTFE=TRUE -DRPI4=TRUE
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_3f826/fast && /usr/bin/make -f CMakeFiles/cmTC_3f826.dir/build.make CMakeFiles/cmTC_3f826.dir/build
    make[1]: Entering directory '/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_3f826.dir/testCCompiler.c.o
    /usr/bin/cc   -m32    -o CMakeFiles/cmTC_3f826.dir/testCCompiler.c.o   -c /home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp/testCCompiler.c
    cc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
    make[1]: *** [CMakeFiles/cmTC_3f826.dir/build.make:66: CMakeFiles/cmTC_3f826.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_3f826/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build/CMakeFiles/CMakeError.log".
```

so i changed what it said, 
``cc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?``

and i got this 
```
pi@retropie:~/SeriousSamClassic/SamTFE/Sources $ ./build-linux32.sh -DTFE=TRUE -DRPI4=TRUE
Will build with 'make -j4' ... please edit this script if incorrect.
+ rm -rf cmake-build
+ mkdir cmake-build
+ cd cmake-build
+ cp -vfr ../Entities/PlayerWeapons_old.es ../Entities/PlayerWeapons.es
'../Entities/PlayerWeapons_old.es' -> '../Entities/PlayerWeapons.es'
+ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-mbe32 -DCMAKE_CXX_FLAGS=-mbe32 -DUSE_I386_NASM_ASM=FALSE .. -DTFE=TRUE -DRPI4=TRUE
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found SDL2: /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11")
-- Using assembler code (when available)
-- Not using i386 nasm ASM
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/SeriousSamClassic/SamTFE/Sources/cmake-build
+ echo 'ECC first'
ECC first
+ make ecc
Scanning dependencies of target ecc
[  0%] Building CXX object CMakeFiles/ecc.dir/Ecc/Main.cpp.o
cc1plus: error: unrecognized -mtune target: generic
cc1plus: note: valid arguments are: arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm7d arm7di arm70 arm700 arm700i arm710 arm720 arm710c arm7100 arm7500 arm7500fe arm7m arm7dm arm7dmi arm8 arm810 strongarm strongarm110 strongarm1100 strongarm1110 fa526 fa626 arm7tdmi arm7tdmi-s arm710t arm720t arm740t arm9 arm9tdmi arm920 arm920t arm922t arm940t ep9312 arm10tdmi arm1020t arm9e arm946e-s arm966e-s arm968e-s arm10e arm1020e arm1022e xscale iwmmxt iwmmxt2 fa606te fa626te fmp626 fa726te arm926ej-s arm1026ej-s arm1136j-s arm1136jf-s arm1176jz-s arm1176jzf-s mpcorenovfp mpcore arm1156t2-s arm1156t2f-s cortex-m1 cortex-m0 cortex-m0plus cortex-m1.small-multiply cortex-m0.small-multiply cortex-m0plus.small-multiply generic-armv7-a cortex-a5 cortex-a7 cortex-a8 cortex-a9 cortex-a12 cortex-a15 cortex-a17 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 cortex-m7 cortex-m4 cortex-m3 marvell-pj4 cortex-a15.cortex-a7 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 exynos-m1 xgene1 cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a55 cortex-a75 cortex-a75.cortex-a55 cortex-m23 cortex-m33 cortex-r52 native
make[3]: *** [CMakeFiles/ecc.dir/build.make:78: CMakeFiles/ecc.dir/Ecc/Main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:374: CMakeFiles/ecc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:381: CMakeFiles/ecc.dir/rule] Error 2
make: *** [Makefile:294: ecc] Error 2
```

i did try the 64bit just cuz but i get a error, as i would excpect

**Comment by tx00100xt** [comment]
The 64 bit version of the game worked under Raspberry Pi4 on Ububuntu 22 LTS (arm64) https://github.com/tx00100xt/SeriousSamClassic-VK/issues/3
amd worked under RPiOS x64 https://github.com/tx00100xt/SeriousSamClassic/issues/7
>cc1plus: error: unrecognized -mtune target: generic
cc1plus: note: valid arguments are: arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm7d arm7di arm70 arm700 arm700i arm710 arm720 arm710c arm7100 arm7500 arm7500fe arm7m arm7dm arm7dmi arm8 arm810 strongarm strongarm110 strongarm1100 strongarm1110 fa526 fa626 arm7tdmi arm7tdmi-s arm710t arm720t arm740t arm9 arm9tdmi arm920 arm920t arm922t arm940t ep9312 arm10tdmi arm1020t arm9e arm946e-s arm966e-s arm968e-s arm10e arm1020e arm1022e xscale iwmmxt iwmmxt2 fa606te fa626te fmp626 fa726te arm926ej-s arm1026ej-s arm1136j-s arm1136jf-s arm1176jz-s arm1176jzf-s mpcorenovfp mpcore arm1156t2-s arm1156t2f-s cortex-m1 cortex-m0 cortex-m0plus cortex-m1.small-multiply cortex-m0.small-multiply cortex-m0plus.small-multiply generic-armv7-a cortex-a5 cortex-a7 cortex-a8 cortex-a9 cortex-a12 cortex-a15 cortex-a17 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 cortex-m7 cortex-m4 cortex-m3 marvell-pj4 cortex-a15.cortex-a7 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 exynos-m1 xgene1 cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a55 cortex-a75 cortex-a75.cortex-a55 cortex-m23 cortex-m33 cortex-r52 native
>
You need to open the CMakeLists.txt file in the editor, find the line:  https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/CMakeLists.txt#L105
>add_compile_options(-mtune=generic)
> 
and replace it with 
>add_compile_options(-march=native )
>

**Comment by Exarkuniv** [comment]
I changed what you told me, and i was able to get TFE to compile just fine, (just need to get the game files now, lol)

but when i try to compile TSE it errors out. 
```
[ 54%] Linking CXX shared library Debug/libEntitiesMP.so
[ 74%] Built target EntitiesMP
make: *** [Makefile:130: all] Error 2
```
whats the command to get a output so i can get you more details.

**Comment by tx00100xt** [comment]
> I changed what you told me, and i was able to get TFE to compile just fine, (just need to get the game files now, lol)
> 
> but when i try to compile TSE it errors out.
> 
> ```
> [ 54%] Linking CXX shared library Debug/libEntitiesMP.so
> [ 74%] Built target EntitiesMP
> make: *** [Makefile:130: all] Error 2
> ```
> 
> whats the command to get a output so i can get you more details.

It is necessary to remove the restriction on the number of displayed lines from the console (terminal), then the entire compilation process will be visible from the very beginning.

**Comment by Exarkuniv** [comment]
``
remove the restriction
``
any thought on how to do that,

**Comment by Exarkuniv** [comment]
Never mind, i did a clean load and figured out what i did wrong]

when i did this part i did not change it from mtune to march
```
    add_compile_options(-mtune=generic)

and replace it with

    add_compile_options(-march=native )
```

this time it compiled just fine, ill test it tomorrow to see if it plays

**Comment by tx00100xt** [comment]
I added changes to build the 32 bit version under RPI4.
SeriousSamClassic: https://github.com/tx00100xt/SeriousSamClassic/commit/c7ba929ee8193d8ce56167b1f3aabc9a0f6261e4
SeriousSamClassic-VK: https://github.com/tx00100xt/SeriousSamClassic-VK/commit/dd84a2180bd0cccaa5d74e3c19503dc75752dbbe

**Comment by Exarkuniv** [comment]
want to say thanks for your help. it have it working on my Pi4
question, is there a way to have this run with software for the graphics or is it only openGL. 
just tring to see if we can get a smoother play at full screen

**Comment by tx00100xt** [comment]
This is an Opengl version, and there  [https://github.com/tx00100xt/SeriousSamClassic-VK](url) is an Opengl and Vulkan version.
The 64 bit version is much faster than the 32 bit version. If possible, better use the 64 bit version.

**Comment by Exarkuniv** [comment]
i would use the 64bit version but the OS for RetroPie is 32bit for now, they are working on the 64bit version but no ETA

so for now ill make a install script, so the work is done and once 64bit retropie is released i will change it over to the 64bit verion for SSAM

**Comment by Exarkuniv** [comment]
so i wanted to see if i could build the 64bit version since you said it runs better.
both TFE and TSE compile fine(as far as i know) 
so when i try to start TFE i get a error about missing file ``sam_menulogo256a_demo.tex``

what is it looking for?

**Comment by tx00100xt** [comment]
>sam_menulogo256a_demo.tex
>
Did you use the build-linux32demo.sh script?
It is intended only for building a demo version of the game.
This script edits here https://github.com/tx00100xt/SeriousSamClassic/blob/main/build-linux32demo.sh#L17

To build the whole game, you need to use SeriousSamClassic/SamTFE/Sources/build-linux32.sh
If the build-linux32demo.sh script was run, the repository needs to be cloned again.

**Comment by Exarkuniv** [comment]
That's the funny thing.
I didnt use that script. 

I used the 64bit script in the TSE folder

**Comment by Exarkuniv** [comment]
i did a clean load and build using build64.sh. it went fine and it plays great. 
just like you said it would. it is very smooth

not sure why the first time i tried to compile it, it failed but it works now. 
sorry for the waste of time. 

oh one other thing. is there away to change where it looks for the data files?

**Comment by tx00100xt** [comment]
> oh one other thing. is there away to change where it looks for the data files?

https://bugs.gentoo.org/854567#c13  https://forums.gentoo.org/viewtopic-t-1151780.html?sid=114aa5eb9c5bbadb01b4172274cad02e
Instead of /usr/lib(64) you can use /usr/lib/x86_64-linux-gnu
https://github.com/tx00100xt/SeriousSamClassic/commit/7b79d07ca287957b84fb9b673adb51e51aa8faab#diff-86a4c082826a1d55a8dc1db512b36a1d72091b073d752b2679234d296638d500L596

**Comment by Exarkuniv** [comment]
Thanks for that. I'll take a look and see if I can figure it out

**Comment by tx00100xt** [comment]
For based on Debian/Ubuntu:

For TFE (Folder  Bin):
SeriousSam -> /usr/bin/serioussam
libEngine.so ->  /usr/lib/x86_64-linux-gnu/serioussam/libEngine.so
libEntities.so ->  /usr/lib/x86_64-linux-gnu//serioussam/libEntities.so
libGame.so ->  /usr/lib/x86_64-linux-gnu//serioussam/libGame.so
Data files:
All game data (content from CD) -> /usr/share/serioussam/

For TSE (Folder  Bin):
SeriousSam -> /usr/bin/serioussamse
libEngineMP.so ->  /usr/lib/x86_64-linux-gnu/serioussamse/libEngineMP.so
libEntitiesMP.so ->  /usr/lib/x86_64-linux-gnu//serioussamse/libEntitiesMP.so
libGameMP.so ->  /usr/lib/x86_64-linux-gnu//serioussamse/libGameMP.so
Data files:
All game data (content from CD) -> /usr/share/serioussamse/

libamp11lib.so -> /usr/lib/x86_64-linux-gnu/libamp11lib.so
libShaders.so -> /usr/lib/x86_64-linux-gnu/libShaders.so

**Comment by Exarkuniv** [comment]
> For based on Debian/Ubuntu:
> 
> For TFE (Folder Bin): SeriousSam -> /usr/bin/serioussam libEngine.so -> /usr/lib/x86_64-linux-gnu/serioussam/libEngine.so libEntities.so -> /usr/lib/x86_64-linux-gnu//serioussam/libEntities.so libGame.so -> /usr/lib/x86_64-linux-gnu//serioussam/libGame.so Data files: All game data (content from CD) -> /usr/share/serioussam/
> 
> For TSE (Folder Bin): SeriousSam -> /usr/bin/serioussamse libEngineMP.so -> /usr/lib/x86_64-linux-gnu/serioussamse/libEngineMP.so libEntitiesMP.so -> /usr/lib/x86_64-linux-gnu//serioussamse/libEntitiesMP.so libGameMP.so -> /usr/lib/x86_64-linux-gnu//serioussamse/libGameMP.so Data files: All game data (content from CD) -> /usr/share/serioussamse/
> 
> libamp11lib.so -> /usr/lib/x86_64-linux-gnu/libamp11lib.so libShaders.so -> /usr/lib/x86_64-linux-gnu/libShaders.so

does that get install there from just running the ``./build-linux64.sh -DTFE=TRUE -DRPI4=TRUE``

**Comment by Exarkuniv** [comment]
thank you for all your help, for the most part i have it working the way i need it to, just messing with linking the folders for easy file placement.

again thanks

**Comment by tx00100xt** [comment]
It's good that it works. I made one mistake with the path for the libEngine.so and libEngineMP.so libraries. They need to be placed in /usr/lib/x86_64-linux-gnu/.
>libEngine.so -> /usr/lib/x86_64-linux-gnu/libEngine.so
libEngineMP.so -> /usr/lib/x86_64-linux-gnu/libEngineMP.so
